name: Test Registry Events
on:
  registry_package:
    types: [published, updated]  
    
concurrency:
  group: ${{ contains(github.event.registry_package.package_version.container_metadata.tag.name || '', 'aux-') && 'grupo' }}
  cancel-in-progress: true
  
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event: ${{ github.event_name }}"
          echo "Tag: ${{ github.event.registry_package.package_version.version }}"
          echo "Tag name: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}"
          echo "Data: ${{ github.event.registry_package.package_version.container_metadata }}"
          echo "Run ID: ${{ github.run_id }}"
